/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoinIdRouteImport } from './routes/coin.$id'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as ApiPublicHooksCheckAlertsRouteImport } from './routes/api/public/hooks/check-alerts'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinIdRoute = CoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksCheckAlertsRoute =
  ApiPublicHooksCheckAlertsRouteImport.update({
    id: '/api/public/hooks/check-alerts',
    path: '/api/public/hooks/check-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/news': typeof NewsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/news': typeof NewsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/news': typeof NewsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculators'
    | '/news'
    | '/alerts'
    | '/portfolio'
    | '/transactions'
    | '/coin/$id'
    | '/api/public/hooks/check-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculators'
    | '/news'
    | '/alerts'
    | '/portfolio'
    | '/transactions'
    | '/coin/$id'
    | '/api/public/hooks/check-alerts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calculators'
    | '/news'
    | '/_authenticated/alerts'
    | '/_authenticated/portfolio'
    | '/_authenticated/transactions'
    | '/coin/$id'
    | '/api/public/hooks/check-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculatorsRoute: typeof CalculatorsRoute
  NewsRoute: typeof NewsRoute
  CoinIdRoute: typeof CoinIdRoute
  ApiPublicHooksCheckAlertsRoute: typeof ApiPublicHooksCheckAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$id': {
      id: '/coin/$id'
      path: '/coin/$id'
      fullPath: '/coin/$id'
      preLoaderRoute: typeof CoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/check-alerts': {
      id: '/api/public/hooks/check-alerts'
      path: '/api/public/hooks/check-alerts'
      fullPath: '/api/public/hooks/check-alerts'
      preLoaderRoute: typeof ApiPublicHooksCheckAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculatorsRoute: CalculatorsRoute,
  NewsRoute: NewsRoute,
  CoinIdRoute: CoinIdRoute,
  ApiPublicHooksCheckAlertsRoute: ApiPublicHooksCheckAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
